image: node:14

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  stage: deploy
  variables: 
    PUBLIC_URL: http://nubloom.xyz/
  script:
    - npm install
    - npm run build
    - npm run export
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
    - public
  only:
    - master
